print("***Ficha de ingreso.***")
print("")
FEC = input("Fecha:")
HOR = input("Hora:")
print("")
print("***Datos del administrativo.***")
print("")
N_AD = input("Nombre:")
A_AD = input("Apellido:")
R_AD = int(input("RUT:"))
F_AD = int(input("Fono:"))
print("")
print("Datos del paciente.")
print("")
N_U_PA = input("Nivel de urgencia:")
N_PA = input("Nombre:")
A_PA = input("Apellido:")
R_PA = int(input("RUT:"))
E_S_PA = input("Estado civil:")
D_PA = input("Domicilio:")
F_PA = int(input("Fono:"))
S_PA = input("Sexo:")
E_PA = int(input("Edad:"))
G_PA = input("Grupo sanguineo:")
AC_PA = input("Asiste acompañado:")
print("")
if AC_PA== "si" :
    print("Datos acompañante.")
    print("")
    N_AC = input("Nombre:")
    R_AC = input("RUT:")
    G_P_AC = input("Grado de parentezco:")
    F_AC = input("Fono:")

if AC_PA== "no" :
    print("")
    
M_C = input("Motivo de consulta medica:")
print("")
print(f"Descripcion del paciente: El paciente {N_PA} {A_PA} de RUT {R_PA} tiene {E_PA} años de edad, su grupo sanguineo es {G_PA} y su nivel de urgencia es {N_U_PA}.")
print("")
print("Informacion de atencion.")
print("")
N_ME = input("Nombre del medico:")
A_ME = input("Apellido del medico:")
R_ME = input("RUT:")
H_AT = input("Horario de atencion:")
T_ME = input("Titulo:")
INS_ME = input("Intitucion donde obtuvo el titulo:")
ES_ME = input("Especialidades:")
A_ME = input("Año de egreso:")
A_T_ME = input("Año/s de trabajo:")
F_ME = input("Fono:")
D_ME = input("Direccion:")
print("")
S_D = input("Sintomas detectados:")
print("")
DIAG = input("Diagsnotico:")
RE = input("reposo:")
if RE == "si" :
    input("Cantidad de dias:")
if RE == "no" :
    print("")
print("")
print("Informacion de medicamento/s.")
M_A_M = input("Medico asigna medicamentos:")
if M_A_M == "si" :
    input("Nombre de medicamento:")
    input("Dosis:")
    input("Cantidad de dias:")
if M_A_M == "no" :
    print("Gracias por su visita.")
    
